name: Release

on:
  push:
    branches: [ master ]
    tags:
      - 'v*'

permissions:
  contents: write 

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      run: cargo test --verbose
    #- name: Check for warnings
    #  run: cargo clippy --all-targets --all-features -- -D warnings
    - name: Doc tests
      run: cargo test --doc

  release:
  name: Build & Release
  needs: test
  if: startswith(github.ref, 'refs/tags/v')
  runs-on: ubuntu-latest

  strategy:
    matrix:
      include:
        - target: x86_64-unknown-linux-gnu
          os: ubuntu-latest
          ext: ''
        - target: x86_64-apple-darwin
          os: macos-latest
          ext: ''
        - target: x86_64-pc-windows-msvc
          os: windows-latest
          ext: '.exe'

  runs-on: ${{ matrix.os }}

  steps:
    - uses: actions/checkout@v4

    - name: Install Rust target
      run: rustup target add ${{ matrix.target }}

    - name: Build binary
      run: cargo build --release --target ${{ matrix.target }}

    - name: Rename binary
      run: |
        mkdir dist
        cp target/${{ matrix.target }}/release/duplicate_file_finder dist/duplicate_file_finder-${{ matrix.target }}${{ matrix.ext }}
      shell: bash

    - name: Upload Release Asset
      uses: softprops/action-gh-release@v1
      with:
        generate_release_notes: true
        name: ${{ github.ref_name }}
        files: dist/*
